/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.pkg3.re.generadorclaves;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Cañamaque
 */
public class generarClaves extends javax.swing.JFrame {

    /**
     * Creates new form generarClaves
     */
    public generarClaves() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        textoLongitud = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        selector = new javax.swing.JComboBox();
        mayus = new javax.swing.JCheckBox();
        rep = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Longitud:");

        jButton1.setText("Generar Contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfabetica", "Alfanumerica", "Numerica", "Completa" }));

        mayus.setText("Sólo Mayusculas");

        rep.setText("Repetible");

        area.setColumns(20);
        area.setLineWrap(true);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mayus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rep))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mayus)
                    .addComponent(rep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        System.out.println("");
        int longitud=0;
        try{
            longitud=Integer.valueOf(textoLongitud.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Introduzca una longitud");
        }
        String contraseña="";
        String caracterAñadir="";
        boolean error=false;
        Random rnd=new Random();
        int tipo=selector.getSelectedIndex();
        
            for (int i = 0; i < longitud; i++) {
                switch(tipo){
                    case 0:
                        
                        if (mayus.isSelected()){
                            if(longitud>26 && !rep.isSelected()){
                                error=true;
                                i=longitud;
                            }else{
                                caracterAñadir=""+(char)(rnd.nextInt('Z'-'A'+1)+'A');
                            }
                            
                        }else{
                            if(longitud>52 && !rep.isSelected()){
                                error=true;
                                i=longitud;
                            }else{
                                if(rnd.nextInt(2)==0){
                                caracterAñadir=""+(char)(rnd.nextInt('Z'-'A'+1)+'A');
                                }else{
                                caracterAñadir=""+(char)(rnd.nextInt('z'-'a'+1)+'a'); 
                                }
                            }                                                  
                        }
                        break;
                    case 1:
                        if(longitud>62 && !rep.isSelected()&& !mayus.isSelected()){
                            error=true;
                            i=longitud;
                        }else{
                            if(rnd.nextInt(2)==0){
                                caracterAñadir=""+(char)(rnd.nextInt('9'-'0'+1)+'0');
                            }else{
                                if(mayus.isSelected()){
                                    if(longitud>36 && !rep.isSelected()){
                                        error=true;
                                        i=longitud;
                                    }else{                                    
                                    caracterAñadir=""+(char)(rnd.nextInt('Z'-'A'+1)+'A');
                                    }
                                }else{
                                    if(rnd.nextInt(2)==0){
                                    caracterAñadir=""+(char)(rnd.nextInt('Z'-'A'+1)+'A');
                                    }else{
                                    caracterAñadir=""+(char)(rnd.nextInt('z'-'a'+1)+'a'); 
                                    }
                                }                         
                            }
                        }
                        break;
                    case 2:
                        if(longitud>10 && !rep.isSelected()){
                            error=true;
                            i=longitud;
                        }else{
                            caracterAñadir=""+(char)(rnd.nextInt('9'-'0'+1)+'0');
                        }
                        break;
                    case 3:
                        if(longitud>94 && !rep.isSelected()){
                            error=true;
                            i=longitud;
                        }else{
                            caracterAñadir=""+(char)(rnd.nextInt('~'-'!'+1)+'!');
                        }
                        break;
                }
                if((contraseña.contains(""+caracterAñadir))&&!rep.isSelected()){
                    i--;
                }else{
                    contraseña+=caracterAñadir;
                }
            }
            if(error==true){
               JOptionPane.showMessageDialog(this, "Longitud invalida"); 
            }
            area.setText(contraseña);
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generarClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generarClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generarClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generarClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generarClaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mayus;
    private javax.swing.JCheckBox rep;
    private javax.swing.JComboBox selector;
    private javax.swing.JTextField textoLongitud;
    // End of variables declaration//GEN-END:variables
}
